driver:
  - piontcloud_to_laserscan
  - ranger_ros2
  - raspi_hc_sr04
  - realsense_ros2
  - static_tf
  - unilidar_L2
capability:
  - amcl
  - map_server
  - navigation2
  - activator
  - vision
skill:
  - move
  - test_skill
brain:
  - test_brian



