amcl:
  ros__parameters:
    use_sim_time: false
    tf_broadcast: true
    scan_topic: /scanner/scan
    min_particles: 300
    max_particles: 2000
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    global_frame_id: "map"
    laser_max_range: -1.0
    laser_min_range: -1.0
    update_min_d: 0.05
    update_min_a: 0.05
    resample_interval: 1
    set_initial_pose: true
    initial_pose:
      x: 3.2
      y: -1.3
      z: 0.0
      yaw: 0.0

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: ""

map_saver:
  ros__parameters:
    use_sim_time: false
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: true


planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
    tf_buffer_duration: 0.5  # ç§’

    
controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 5.0
    # min_x_velocity_threshold: 0.01
    # min_y_velocity_threshold: 0.01
    # min_theta_velocity_threshold: 0.01
    failure_tolerance: 0.5
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"] # "precise_goal_checker"
    controller_plugins: ["FollowPath"]

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.1
      movement_time_allowance: 30.0
    # Goal checker parameters
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
    # DWB parameters
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: 0.00
      min_vel_y: 0.0
      max_vel_x: 0.3
      max_vel_y: 0.0
      max_vel_theta: 0.6
      # min_vel_theta: 0.05
      min_speed_xy: 0.0
      max_speed_xy: 0.4
      min_speed_theta: 0.05
      # Add high threshold velocity for turtlebot 3 issue.
      # https://github.com/ROBOTIS-GIT/turtlebot3_simulations/issues/75
      acc_lim_x: 0.5
      acc_lim_y: 0.0
      acc_lim_theta: 1.0
      decel_lim_x: -0.5
      decel_lim_y: -0.0
      decel_lim_theta: -1.0
      vx_samples: 20
      vy_samples: 5
      vtheta_samples: 360
      sim_time: 3.0
      linear_granularity: 0.05
      angular_granularity: 0.05
      transform_tolerance: 0.5
      # xy_goal_tolerance: 0.25
      # yaw_goal_tolerance: 0.25
      # trans_stopped_velocity: 0.15
      short_circuit_trajectory_evaluation: True
      stateful: True
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle.scale: 0.015
      PathAlign.scale: 1.0
      # PathAlign.forward_point_distance: 0.1
      # PathAlign.forward_preference: true
      GoalAlign.scale: 0.2
      # GoalAlign.forward_point_distance: 0.1
      # GoalAlign.forward_preference: true
      PathDist.scale: 0.5
      GoalDist.scale: 2.0
      RotateToGoal.xy_goal_tolerance: 0.20
      RotateToGoal.scale: 1.0
      RotateToGoal.slowing_factor: 1.0
      RotateToGoal.lookahead_time: 0.5
    

bt_navigator:
  ros__parameters:
    use_sim_time: false
    default_bt_xml_filename: "./config/my_navigate_w_replanning_and_recovery.xml"
    tf_buffer_duration: 0.5

recoveries_server:
  ros__parameters:
    costmap_topic: global_costmap/costmap
    footprint_topic: global_costmap/published_footprint

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 10.0
      publish_frequency: 10.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: false
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      footprint: "[ [0.34, 0.23], [0.34, -0.23], [-0.34, -0.23], [-0.34, 0.23] ]"
      footprint_padding: 0.05
      # robot_radius: 0.32
      
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /scanner/scan
          max_obstacle_height: 2.0
          marking: true
          clearing: true

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.60


global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: map          # é€šå¸¸æ˜¯ map
      robot_base_frame: base_link
      # robot_radius: 0.32
      footprint: "[ [0.34, 0.23], [0.34, -0.23], [-0.34, -0.23], [-0.34, 0.23] ]"
      footprint_padding: 0.05
      update_frequency: 1.0      # æ›´æ–°é¢‘ç‡ï¼ˆHzï¼‰ï¼Œæ¯” local_costmap ä½å³å¯
      publish_frequency: 1.0     # å‘å¸ƒé¢‘ç‡
      resolution: 0.05           # åˆ†è¾¨ç‡ï¼Œå»ºè®®å’Œåœ°å›¾ä¸€è‡´

      rolling_window: false      # ğŸš« ä¸è¦æ»šåŠ¨ï¼Œé€šå¸¸è®¾ç½®ä¸º false
      track_unknown_space: true  # è·¯å¾„è§„åˆ’æ—¶æ˜¯å¦è€ƒè™‘æœªçŸ¥åŒºåŸŸ
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
        enabled: true

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /scanner/scan
          max_obstacle_height: 2.0
          marking: true
          clearing: true

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 2.00


lifecycle_manager:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names:
      - planner_server
      - controller_server
      - bt_navigator
      - recoveries_server
